language: minimal
os: osx
osx_image: xcode11.3
install:
  - brew uninstall python
  - brew cleanup
  - rm /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
  - wget -O /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb https://gist.githubusercontent.com/dhinakg/c4f0acebafc27c93dc40f2054d8a63a4/raw/21d9eebc3f15c7a0069ec0f51d2e08ed6a168263/python-with-tcl.rb
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source python
script:
  - pyinstaller ProperTree.spec
  - ./after_pyinstaller.sh
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew
before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
# Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
# Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi