language: minimal
os: osx
osx_image: xcode11.3
install:
  - brew uninstall --ignore-dependencies python
  - brew cleanup
  - rm /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
  - wget -O /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb https://gist.githubusercontent.com/dhinakg/c4f0acebafc27c93dc40f2054d8a63a4/raw/21d9eebc3f15c7a0069ec0f51d2e08ed6a168263/python-with-tcl.rb
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install --build-from-source python
  - pip3 install pyinstaller
script:
- pyinstaller ProperTree.spec
- "./after_pyinstaller.sh"
cache:
  directories:
  - "$HOME/Library/Caches/Homebrew"
  - "/usr/local/Homebrew"
before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
# Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
# Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
before_deploy:
  - zip -r -X ProperTree.app.zip dist/ProperTree.app
  - git tag "$(git log --format=%h -1)"
deploy:
  skip_cleanup: true
  provider: releases
  if: tag IS blank
  api_key:
    secure: fVVEPw77vsVZAZVTCIUwnnXjIKkfju9uRN63TV5QC9EVGLxlS1M7jfJuoZgxNG1Hu8dvrQG+BMM6M8qCGY4UwOg+Y1X0TvKtgP04GUATbEM/RY9iLpvht6/QO9HHGVnHZ40WjQIGeH6pmrxOBSQu4OImZyDe8ZgeZArj4qGIia4sAy79KiagRtTepGxfHXqdKEzXgO1Rkcwbs/yaOpYHUgpUEreXqsYYnWxaUAO1hE6Ht+RBQIc0nO21iS1DjGMYbLacNvs3HcZ0w9Qa9iRAp+beQvzvitn46cqdlczDvs7r7Ptw8N+K3uKYCYkEXBBR9zJWyeVrGUKqV9UPSEHVjNNrZo+MY+J/DYW47MSsCmlrWiUzxO4usLuBmr05Jtxo8tdZ0r9oN6s7rkDcnRzPGWTdV2zs89Y1jf12+oAe+NsCFsDVU+umOcRBTW/fvfphIJhB5cKM/bjs8NmZri6ozCytL1SyEOGVSlzMwAvm/T1gA2jtd4mbGpJrSTO4Mn7o7J4qV4Yn6G95narQpTsYZkgD1MiknFEh2NZV4shGaECtOG8ABmO0gd3B7ntjI5TT4nvhKwYGEXycpxQcwi3O/8CjXSLm2HmI6Sq8+2LDZKML7gN3wYARN1K+EZsuwYWDeesz7x/JtIzMJqUcYLcfJTt5DlCWY2tM71jP09Da8I=
  file: ProperTree.app.zip
  on:
    repo: dhinakg/ProperTree
